
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1024
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
